name: angular_image_compare
description: An Angular Dart component allowing easy visual comparison of two images.
version: 0.1.0
#homepage: https://www.example.com
#author: Matthew <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular2: ^3.1.0
  angular_components: ^0.5.3

dev_dependencies:
  test: ^0.12.0

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart