name: angular_image_compare
description: An Angular Dart component allowing easy visual comparison of two images.
version: 0.2.0
#homepage: https://www.example.com
#author: Matthew <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.7.0

dev_dependencies:
  test: ^0.12.0

transformers:
- angular:
    entry_points: web/main.dart